modules:
  - name: vim
    install:
      - pacman:vim
      - apt:vim
    config: ~/.vimrc

  - name: shell
    exec: |
      local dirs=(
        ~/bin
        ~/bin/local_scripts
        ~/downloads
      )
      for dir in "${dirs[@]}"; do
        mkdir -p "$dir"
      done

      # ... (etc)

  # points XDG_DOWNLOAD_DIR (used by firefox, chromium, etc) at ~/downloads
  - name: user-dirs
    config: ~/.config/user-dirs.dirs
